graphql {
  schema {
    // this is a required property that you need to set to appropriate value
    // example value is just provided for illustration purposes
    packages = [
    ]
    federation {
      enabled = false
      tracing {
        enabled = true
        debug = false
      }
    }
  }
  engine {
    automaticPersistedQueries {
      enabled = false
    }
    batching {
      enabled = false
      strategy = LEVEL_DISPATCHED
    }
    introspection {
      enabled = true
    }
  }
}