#schema {
#    query: Query
#    mutation: Mutation
#}
#
#type Query {
#    users: [UserType]
#}
#
#type Mutation {
#    createUser(name: String, email: String): UserType
#}

# Inputs

#input UserInput {
#    id: ID!
#    name: String
#    email: String
#    profilePhoto: ProfilePhotoInput
#    voiceRecordings: [VoiceRecordingInput]
#    proustResponses: [ProustResponseInput]
#    dateDetails: [DateDetailInput]
#    reflections: [ReflectionInput]
#}
#
#input ProfilePhotoInput {
#    id: ID!
#    url: String
#    userId: ID!
#}
#
#input VoiceRecordingInput {
#    id: ID!
#    url: String
#    userId: ID!
#}
#
#input ProustQuestionnaireInput {
#    id: ID!
#    questions: [String]
#}
#
#input ProustResponseInput {
#    id: ID!
#    questionnaireId: ID!
#    userId: ID!
#    responses: [String]
#}
#
#input DateDetailInput {
#    id: ID!
#    userId: ID!
#    date: String
#    location: String
#    details: String
#}
#
#input ReflectionInput {
#    id: ID!
#    userId: ID!
#    dateDetailId: ID!
#    reflection: String
#}

# Output Types
#
#type UserType {
#    id: ID!
#    name: String
#    email: String
#    profilePhoto: ProfilePhotoType
#    voiceRecordings: [VoiceRecordingType]
#    proustResponses: [ProustResponseType]
#    dateDetails: [DateDetailType]
#    reflections: [ReflectionType]
#}
#
#type ProfilePhotoType {
#    id: ID!
#    url: String
#    userId: ID!
#}
#
#type VoiceRecordingType {
#    id: ID!
#    url: String
#    userId: ID!
#}
#
#type ProustQuestionnaireType {
#    id: ID!
#    questions: [String]
#}
#
#type ProustResponseType {
#    id: ID!
#    questionnaireId: ID!
#    userId: ID!
#    responses: [String]
#}
#
#type DateDetailType {
#    id: ID!
#    userId: ID!
#    date: String
#    location: String
#    details: String
#}
#
#type ReflectionType {
#    id: ID!
#    userId: ID!
#    dateDetailId: ID!
#    reflection: String
#}